#include <iostream>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>
#include <map>
#include <set>
#include <algorithm>
#include <chrono>
#include <iomanip>
#include <cmath>
#include <memory>
#include <functional>

namespace ais {

// Constants for gap detection
constexpr double MAX_TIME_GAP_SECONDS = 30.0;      // Max expected time between fixes
constexpr double POSITION_THRESHOLD_NM = 15.0;      // Max position jump (nautical miles)
constexpr double VELOCITY_THRESHOLD_KNOTS = 60.0;   // Max velocity (knots)

// NMEA sentence types we care about
enum class SentenceType {
    GGA,     // GPS fix data
    GSA,     // DOP and active satellites
    GSV,     // Satellite in view
    RMB,     // Recommended minimum navigation position
    VTG,     // Course over ground
    VWR,     // Water speed over ground
    ZDA,     // Time of day and date
    VDM,     // Binary data message (NMEA 0183)
    VDO,     // Binary data message (NMEA 0183)
    VDW,     // Binary data message (NMEA 0183)
    VDL,     // Binary data message (NMEA 0183)
    VDR,     // Binary data message (NMEA 0183)
    VDT,     // Binary data message (NMEA 0183)
    VDX,     // Binary data message (NMEA 0183)
    VDA,     // Binary data message (NMEA 0183)
    VDB,     // Binary data message (NMEA 0183)
    VDC,     // Binary data message (NMEA 0183)
    VDD,     // Binary data message (NMEA 0183)
    VDE,     // Binary data message (NMEA 0183)
    VDF,     // Binary data message (NMEA 0183)
    VDG,     // Binary data message (NMEA 0183)
    VDH,     // Binary data message (NMEA 0183)
    VDI,     // Binary data message (NMEA 0183)
    VDJ,     // Binary data message (NMEA 0183)
    VDK,     // Binary data message (NMEA 0183)
    VDL,     // Binary data message (NMEA 0183)
    VDM,     // Binary data message (NMEA 0183)
    VDN,     // Binary data message (NMEA 0183)
    VDO,     // Binary data message (NMEA 0183)
    VDP,     // Binary data message (NMEA 0183)
    VDQ,     // Binary data message (NMEA 0183)
    VDR,     // Binary data message (NMEA 0183)
    VDS,     // Binary data message (NMEA 0183)
    VDT,     // Binary data message (NMEA 0183)
    VDU,     // Binary data message (NMEA 0183)
    VDV,     // Binary data message (NMEA 0183)
    VDW,     // Binary data message (NMEA 0183)
    VDX,     // Binary data message (NMEA 0183)
    VDY,     // Binary data message (NMEA 0183)
    VDZ,     // Binary data message (NMEA 0183)
    VEA,     // Binary data message (NMEA 0183)
    VEB,     // Binary data message (NMEA 0183)
    VEC,     // Binary data message (NMEA 0183)
    VED,     // Binary data message (NMEA 0183)
    VEE,     // Binary data message (NMEA 0183)
    VEF,     // Binary data message (NMEA 0183)
    VEG,     // Binary data message (NMEA 0183)
    VEI,     // Binary data message (NMEA 0183)
    VEJ,     // Binary data message (NMEA 0183)
    VEK,     // Binary data message (NMEA 0183)
    VEL,     // Binary data message (NMEA 0183)
    VEM,     // Binary data message (NMEA 0183)
    VEN,     // Binary data message (NMEA 0183)
    VEO,     // Binary data message (NMEA 0183)
    VEP,     // Binary data message (NMEA 0183)
    VEQ,     // Binary data message (NMEA 0183)
    VER,     // Binary data message (NMEA 0183)
    VES,     // Binary data message (NMEA 0183)
    VET,     // Binary data message (NMEA 0183)
    VEU,     // Binary data message (NMEA 0183)
    VEV,     // Binary data message (NMEA 0183)
    VEW,     // Binary data message (NMEA 0183)
    VEX,     // Binary data message (NMEA 0183)
    VEY,     // Binary data message (NMEA 0183)
    VEZ,     // Binary data message (NMEA 0183)
    VFA,     // Binary data message (NMEA 0183)
    VFB,     // Binary data message (NMEA 0183)
    VFC,     // Binary data message (NMEA 0183)
    VFD,     // Binary data message (NMEA 0183)
    VFE,     // Binary data message (NMEA 0183)
    VFF,     // Binary data message (NMEA 0183)
    VFG,     // Binary data message (NMEA 0183)
    VFI,     // Binary data message (NMEA 0183)
    VFJ,     // Binary data message (NMEA 0183)
    VFK,     // Binary data message (NMEA 0183)
    VFL,     // Binary data message (NMEA 0183)
    VFM,     // Binary data message (NMEA 0183)
    VFN,     // Binary data message (NMEA 0183)
    VFO,     // Binary data message (NMEA 0183)
    VFP,     // Binary data message (NMEA 0183)
    VFQ,     // Binary data message (NMEA 0183)
    VFR,     // Binary data message (NMEA 0183)
    VFS,     // Binary data message (NMEA 0183)
    VFT,     // Binary data message (NMEA 0183)
    VFU,     // Binary data message (NMEA 0183)
    VFW,     // Binary data message (NMEA 0183)
    VFX,     // Binary data message (NMEA 0183)
    VFY,     // Binary data message (NMEA 0183)
    VFZ,     // Binary data message (NMEA 0183)
    VHA,     // Binary data message (NMEA 0183)
    VHB,     // Binary data message (NMEA 0183)
    VHC,     // Binary data message (NMEA 0183)
    VHD,     // Binary data message (NMEA 0183)
    VHE,     // Binary data message (NMEA 0183)
    VHF,     // Binary data message (NMEA 0183)
    VHG,     // Binary data message (NMEA 0183)
    VHI,     // Binary data message (NMEA 0183)
    VHJ,     // Binary data message (NMEA 0183)
    VHK,     // Binary data message (NMEA 0183)
    VHL,     // Binary data message (NMEA 0183)
    VHM,     // Binary data message (NMEA 0183)
    VHN,     // Binary data message (NMEA 0183)
    VHO,     // Binary data message (NMEA 0183)
    VHP,     // Binary data message (NMEA 0183)
    VHQ,     // Binary data message (NMEA 0183)
    VHR,     // Binary data message (NMEA 0183)
    VHS,     // Binary data message (NMEA 0183)
    VHT,     // Binary data message (NMEA 0183)
    VHU,     // Binary data message (NMEA 0183)
    VHW,     // Binary data message (NMEA 0183)
    VHX,     // Binary data message (NMEA 0183)
    VHY,     // Binary data message (NMEA 0183)
    VHZ,     // Binary data message (NMEA 0183)
    VIJ,     // Binary data message (NMEA 0183)
    VIK,     // Binary data message (NMEA 0183)
    VIL,     // Binary data message (NMEA 0183)
    VIM,     // Binary data message (NMEA 0183)
    VIN,     // Binary data message (NMEA 0183)
    VIO,     // Binary data message (NMEA 0183)
    VIP,     // Binary data message (NMEA 0183)
    VIQ,     // Binary data message (NMEA 0183)
    VIR,     // Binary data message (NMEA 0183)
    VIS,     // Binary data message (NMEA 0183)
    VIT,     // Binary data message (NMEA 0183)
    VIU,     // Binary data message (NMEA 0183)
    VIV,     // Binary data message (NMEA 0183)
    VIW,     // Binary data message (NMEA 0183)
    VIX,     // Binary data message (NMEA 0183)
    VIY,     // Binary data message (NMEA 0183)
    VIZ,     // Binary data message (NMEA 0183)
    VJA,     // Binary data message (NMEA 0183)
    VJB,     // Binary data message (NMEA 0183)
    VJC,     // Binary data message (NMEA 0183)
    VJD,     // Binary data message (NMEA 0183)
    VJE,     // Binary data message (NMEA 0183)
    VJF,     // Binary data message (NMEA 0183)
    VJG,     // Binary data message (NMEA 0183)
    VJI,     // Binary data message (NMEA 0183)
    VJJ,     // Binary data message (NMEA 0183)
    VJK,     // Binary data message (NMEA 0183)
    VJL,     // Binary data message (NMEA 0183)
    VJM,     // Binary data message (NMEA 0183)
    VJN,     // Binary data message (NMEA 0183)
    VJO,     // Binary data message (NMEA 0183)
    VJP,     // Binary data message (NMEA 0183)
    VJQ,     // Binary data message (NMEA 0183)
    VJR,     // Binary data message (NMEA 0183)
    VJS,     // Binary data message (NMEA 0183)
    VJT,     // Binary data message (NMEA 0183)
    VJU,     // Binary data message (NMEA 0183)
    VJV,     // Binary data message (NMEA 0183)
    VJW,     // Binary data message (NMEA 0183)
    VJX,     // Binary data message (NMEA 0183)
    VJY,     // Binary data message (NMEA 0183)
    VJZ,     // Binary data message (NMEA 0183)
    VKA,     // Binary data message (NMEA 0183)
    VKB,     // Binary data message (NMEA 0183)
    VKC,     // Binary data message (NMEA 0183)
    VKD,     // Binary data message (NMEA 0183)
    VKE,     // Binary data message (NMEA 0183)
    VKF,     // Binary data message (NMEA 0183)
    VKG,     // Binary data message (NMEA 0183)
    VKI,     // Binary data message (NMEA 0183)
    VKJ,     // Binary data message (NMEA 0183)
    VKK,     // Binary data message (NMEA 0183)
    VKL,     // Binary data message (NMEA 0183)
    VKM,     // Binary data message (NMEA 0183)
    VKN,     // Binary data message (NMEA 0183)
    VKO,     // Binary data message (NMEA 0183)
    VKP,     // Binary data message (NMEA 0183)
    VKQ,     // Binary data message (NMEA 0183)
    VKR,     // Binary data message (NMEA 0183)
    VKS,     // Binary data message (NMEA 0183)
    VKT,     // Binary data message (NMEA 0183)
    VKU,     // Binary data message (NMEA 0183)
    VKV,     // Binary data message (NMEA 0183)
    VKW,     // Binary data message (NMEA 0183)
    VKX,     // Binary data message (NMEA 0183)
    VKY,     // Binary data message (NMEA 0183)
    VKZ,     // Binary data message (NMEA 0183)
    VLA,     // Binary data message (NMEA 0183)
    VLB,     // Binary data message (NMEA 0183)
    VLC,     // Binary data message (NMEA 0183)
    VLD,     // Binary data message (NMEA 0183)
    VLE,     // Binary data message (NMEA 0183)
    VLF,     // Binary data message (NMEA 0183)
    VLG,     // Binary data message (NMEA 0183)
    VLI,     // Binary data message (NMEA 0183)
    VLJ,     // Binary data message (NMEA 0183)
    VLL,     // Binary data message (NMEA 0183)
    VLM,     // Binary data message (NMEA 0183)
    VLN,     // Binary data message (NMEA 0183)
    VLO,     // Binary data message (NMEA 0183)
    VLP,     // Binary data message (NMEA 0183)
    VLQ,     // Binary data message (NMEA 0183)
    VLR,     // Binary data message (NMEA 0183)
    V